/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../src/vue/components/App.vue')['default']
    Container: typeof import('./../src/vue/components/Container.vue')['default']
    Head: typeof import('./../src/vue/components/Head.vue')['default']
    Icon: typeof import('./../src/vue/components/Icon.vue')['default']
    Image: typeof import('./../src/vue/components/Image.vue')['default']
    Layout: typeof import('./../src/vue/components/Layout.vue')['default']
    Link: typeof import('./../src/vue/components/Link.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VulmixWelcome: typeof import('./../src/vue/components/VulmixWelcome.vue')['default']
  }
}
